version: "3"

# build set to current directory
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    # maps volume from local machine into Docker container that will be running application
    # when you change something in local, will map to Docker so that dont need to restart Docker and reflected in Docker
    volumes:
      - ./app:/app
    command: >
      sh -c   "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
